CREATE TABLE IF NOT EXISTS list_links (
	id INTEGER PRIMARY KEY, 
	name TEXT NULL, 
	url TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
	id INTEGER PRIMARY KEY, 
	title TEXT NOT NULL, 
	author TEXT NOT NULL, 
	rating INTEGER DEFAULT 0, 
	rating_count INTEGER DEFAULT 0
);
